# Generated by Django 3.1.3 on 2020-11-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygalleria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='mygalleria_image',
        ),
    ]
