# Generated by Django 3.1.3 on 2020-11-16 09:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygalleria', '0002_auto_20201114_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygalleria_image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='./media', max_length=255, verbose_name='image'),
        ),
    ]
